### ISSUE TITLE
"No Such Key" error when running the t4.Package.install command

### ISSUE THREAD

**Issue by hedgy123** [quiltdata/quilt-sagemaker-demo#4]
Hi,

   I am trying to follow along your instructions from the medium post.  I get to this point:
 
```
    import t4
    t4.Package.install("quilt/fashion_mnist", registry="s3://quilt-example", dest=".")
```

 and then I get the following error:

```
NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

   I tried several different s3 buckets, but I get the same exact error.   Could you please help? 
Thanks so much!

**Comment by akarve** [comment]
Hi There. `t4` was transitionted to `quilt3` a while back, so we recommend that you use `quilt3` from now on. It looks like the package location was updated as well:
https://open.quiltdata.com/b/quilt-example/packages/?filter=fash

If you click on the CODE cell (top) you'll see the new code for installing that data:
https://open.quiltdata.com/b/quilt-example/packages/aleksey/fashion_mnist
